- extensions:
  - default: false
  - name: RankNTypes
  - name: CPP
    within: Velma.SymbolicPath
- flags: [ { default: false } ]
- group: { name: dollar, enabled: true }
- group: { name: generalise, enabled: true }
